Make profile script cluster specific

diff --git a/files/ood/profile_sofia b/files/ood/profile_sofia
--- a/files/ood/profile_sofia
+++ b/files/ood/profile_sofia
@@ -17,19 +17,14 @@ if [ -n "$PUNUSER" ]; then
     if [[ "$1" == "pun" ]] && ! id -Gn "$PUNUSER" 2>/dev/null | grep -qw 'bsofia_projects'; then
         echo "Access denied: $PUNUSER is not authorized to use this system." >&2
         echo "User $PUNUSER is not part of the bsofia_projects group." >&2
-        echo "Please contact the support team if you believe this is an error." >&2
+        echo "Please contact the support team (support@vscentrum.be) if you believe this is an error." >&2
         exit 1
     fi
 
     logger -- "Setting the VSC variables for $PUNUSER"
     eval "$(runuser -u "${PUNUSER}" -- python3 /usr/bin/vsc_env bash)"
 
-    if [ -d "${VSC_DATA}" ]; then
-        export OOD_DATAROOT=${VSC_DATA}/.ondemand/${VSC_INSTITUTE_LOCAL:-data}/
-    else
-        export OOD_DATAROOT="${VSC_SCRATCH}/.ondemand/${VSC_INSTITUTE_LOCAL:-data}/"
-        logger -- "VSC_DATA unavailable for $PUNUSER, using OOD_DATAROOT: $OOD_DATAROOT"
-    fi
+    export OOD_DATAROOT="${VSC_SCRATCH}/.ondemand/${VSC_INSTITUTE_LOCAL:-data}/"
 
     runuser -u "${PUNUSER}" bash /etc/profile.d/vscautokey.sh &
 fi
